name: triggers-practice
run-name: execute-triggers
on:
  push:
    branches: ['main']
  pull_request:
    types:
      - opened
      - labeled
  issues:
    types:
      - opened
      - edited
      - closed
  schedule:
    - cron: '5 * * * *'  # Runs at minute 5 of every hour

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Specify PHP version
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, json, libxml
          coverage: none
      - name: Run PHP script
        run: php prueba.php